import Header from "../../components/Header";
import ProgressStepper from "../../components/ProgressStepper";

function AuthenticatorSetup() {
  return (
    <div className="min-h-screen bg-[#f7f8fc] text-[#171923]">
      <Header />

      <main className="mx-auto flex min-h-[calc(100vh-64px)] max-w-[1180px] items-center justify-center px-5 py-10">
        <section className="w-full max-w-[620px] rounded-xl border border-[#e4e6ed] bg-white px-6 py-8 shadow-[0_2px_12px_rgba(20,20,40,0.04)] sm:px-10">

          {/* Progress */}
          <div className="mb-8">
            <ProgressStepper activeStep={4} />
          </div>

          {/* Heading */}
          <div className="text-center">
            <h1 className="text-[22px] font-bold tracking-[-0.4px]">
              Set up your authenticator
            </h1>

            <p className="mx-auto mt-2 max-w-[430px] text-[12px] leading-5 text-[#777b86]">
              Scan the QR code using your authenticator app to link it
              with your SecureID account.
            </p>
          </div>

          {/* QR Code Placeholder */}
          <div className="mx-auto mt-7 flex h-40 w-40 items-center justify-center rounded-lg border border-[#e1e3e9] bg-white">
            <div className="grid h-32 w-32 grid-cols-7 gap-1 p-2">
              {Array.from({ length: 49 }).map((_, index) => (
                <span
                  key={index}
                  className={
                    [0, 1, 2, 7, 9, 14, 15, 16, 20, 22, 24, 28, 30, 32, 34, 36, 40, 42, 43, 44, 48].includes(
                      index
                    )
                      ? "bg-[#171923]"
                      : "bg-white"
                  }
                />
              ))}
            </div>
          </div>

          {/* Instructions */}
          <div className="mt-7 rounded-lg bg-[#fafbfe] p-5">
            <h2 className="text-[12px] font-semibold text-[#464955]">
              How to set up
            </h2>

            <div className="mt-4 space-y-3">
              <div className="flex gap-3">
                <span className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-[#eef1ff] text-[9px] font-semibold text-[#3155e8]">
                  1
                </span>

                <p className="text-[11px] leading-5 text-[#6d707b]">
                  Open your authenticator app.
                </p>
              </div>

              <div className="flex gap-3">
                <span className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-[#eef1ff] text-[9px] font-semibold text-[#3155e8]">
                  2
                </span>

                <p className="text-[11px] leading-5 text-[#6d707b]">
                  Scan the QR code shown above.
                </p>
              </div>

              <div className="flex gap-3">
                <span className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-[#eef1ff] text-[9px] font-semibold text-[#3155e8]">
                  3
                </span>

                <p className="text-[11px] leading-5 text-[#6d707b]">
                  Enter the 6-digit code generated by the app.
                </p>
              </div>
            </div>
          </div>

          {/* Continue */}
          <button
            type="button"
            className="mt-7 h-[42px] w-full rounded-md bg-[#2449df] text-[12px] font-semibold text-white transition hover:bg-[#1d3dcc]"
          >
            Continue
          </button>

          {/* Footer */}
          <p className="mt-7 text-center text-[9px] text-[#a0a2aa]">
            © 2024 SecureID. All rights reserved.
          </p>
        </section>
      </main>
    </div>
  );
}

export default AuthenticatorSetup;